function(inject_defs_into_schema OUT DEFINITIONS_SCHEMA_JSON_FILE TARGET_SCHEMA_JSON_FILE) 

    file(READ "${DEFINITIONS_SCHEMA_JSON_FILE}" DEFINITIONS_SCHEMA_JSON)
    file(READ "${TARGET_SCHEMA_JSON_FILE}" TARGET_SCHEMA_JSON)

    string(REGEX REPLACE
    "\"\\$ref\".*:.*\".*#\/\\$defs\/"
    "\"\$ref\": \"#\/\$defs\/"
    TARGET_SCHEMA_JSON "${TARGET_SCHEMA_JSON}")

    string(JSON DEFINITIONS GET ${DEFINITIONS_SCHEMA_JSON} "$defs")
    string(JSON TARGET_SCHEMA_WITH_DEFINITIONS_JSON SET ${TARGET_SCHEMA_JSON} "$defs" ${DEFINITIONS})

    # string(REGEX REPLACE "\r?\n" " " TARGET_SCHEMA_WITH_DEFINITIONS_JSON "${TARGET_SCHEMA_WITH_DEFINITIONS_JSON}")
    # string(REGEX REPLACE "\"" "\\\"" TARGET_SCHEMA_WITH_DEFINITIONS_JSON "${TARGET_SCHEMA_WITH_DEFINITIONS_JSON}")
    set(OUTPUT_STRING "R\"json_delimeter(")
    string(APPEND OUTPUT_STRING "${TARGET_SCHEMA_WITH_DEFINITIONS_JSON}")
    string(APPEND OUTPUT_STRING ")json_delimeter\"")
    set(${OUT} "${OUTPUT_STRING}" PARENT_SCOPE)
    
endfunction()
