name: labeler

on: [pull_request]

jobs:
  labeler:
    permissions:
      pull-requests: write
      contents: read
      issues: write
    runs-on: ubuntu-latest
    name: Label the PR
    env:
      MAJOR_LABEL: 'version/major 🏗️'
      MAJOR_PREFIXES: 'release'
      MINOR_LABEL: 'version/minor 🔨'
      MINOR_PREFIXES: 'feature'
      PATCH_LABEL: 'version/patch 🪶'
      PATCH_PREFIXES: 'bugfix task'
    steps: # TODO: add label based on major/minor version
      - name: Display PR branch name
        run: |
          branch="${{github.head_ref}}"
          prefix=${branch%%/*}
          echo "The PR branch name is: ${{ github.head_ref }}, the prefix is: ${prefix}"

          # Check if prefix matches any version prefix
          if [[ "${{ env.MAJOR_PREFIXES }}" == *"$prefix"* ]]; then
              echo "Found major prefix."
              label="${{ env.MAJOR_LABEL }}"
          elif [[ "${{ env.MINOR_PREFIXES }}" == *"$prefix"* ]]; then
              echo "Found minor prefix."
              label="${{ env.MINOR_LABEL }}"
          elif [[ "${{ env.PATCH_PREFIXES }}" == *"$prefix"* ]]; then
              echo "Found patch prefix."
              label="${{ env.PATCH_LABEL }}"
          else
              echo "No matching prefix found!"
          fi
      # - run: gh issue edit "$NUMBER" --add-label "$LABELS"
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GH_REPO: ${{ github.repository }}
      #     NUMBER: ${{ github.event.issue.number }}
      #     LABELS: triage
