name: labeler

on: [pull_request]

jobs:
  labeler:
    permissions:
      pull-requests: write
      contents: read
      issues: write
    runs-on: ubuntu-latest
    name: Label the PR
    steps: # TODO: add label based on major/minor version
      - name: Display PR branch name
        run: echo "The PR branch name is: ${{ github.head_ref }}"
      # - run: gh issue edit "$NUMBER" --add-label "$LABELS"
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GH_REPO: ${{ github.repository }}
      #     NUMBER: ${{ github.event.issue.number }}
      #     LABELS: triage
